---
##########################################################
## Upstairs Automation
##########################################################

     #####################################################
     ## Turn Off Upstairs Bedroom Lights
     #####################################################

- alias: Turn Off Upstairs Bedroom Lights
  initial_state: true
  trigger:
    platform: time
    at: '07:15:00'
  condition:
    condition: state
    entity_id: binary_sensor.workday
    state: 'on'
  action:
  - data:
      entity_id: 
        - light.mary_bedroom_lamp
        - light.abigail_bedroom_lamp
    service: light.turn_off