---
##########################################################
## Master Bedroom Automation
##########################################################

     #####################################################
     ## Bed Presence Input Boolean
     #####################################################

- alias: Bed Presence Input Boolean Turned On
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.eight_left_bed_presence
      to: 'on'
    - platform: state
      entity_id: binary_sensor.eight_right_bed_presence
      to: 'on'
  condition: []
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bed_occupied



- alias: Bed Presence Input Boolean Turned Off Left Side
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.eight_left_bed_presence
    to: 'off'
  condition:
    condition: state
    entity_id: binary_sensor.eight_right_bed_presence
    state: 'off'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bed_occupied

- alias: Bed Presence Input Boolean Turned Off Right Side
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.eight_right_bed_presence
    to: 'off'
  condition:
    condition: state
    entity_id: binary_sensor.eight_left_bed_presence
    state: 'off'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bed_occupied