---
     #####################################################
     ## Master Bedroom Lamps On With Motion
     #####################################################

- alias: Master Bedroom Lamps On with Motion
  initial_state: true
#  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bedroom_sensor_motion
#custom    entity_id: binary_sensor.master_bedroom_motion_sensor
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.bed_occupied
      state: 'off'
    - condition: numeric_state
      entity_id: 'sensor.master_bedroom_sensor_light_level'
      below: 20
  action:
  - data_template:
      entity_id: light.master_bedroom_lamps
      brightness: "{{ states('input_number.light_brightness') | int }}"
      kelvin: "{{ states('input_number.light_kelvin') | int }}"
      transition: 15
    service: light.turn_on
