---
##########################################################
## Master Bedroom Automation
##########################################################

     #####################################################
     ## Bed Presence Input Boolean
     #####################################################

- alias: Bed Presence Input Boolean Turned On
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.eight_left_bed_presence
      to: 'on'
    - platform: state
      entity_id: binary_sensor.eight_right_bed_presence
      to: 'on'
  condition: []
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bed_occupied
          
- alias: Bed Presence Input Boolean Turned Off Left Side
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.eight_left_bed_presence
    to: 'off'
  condition:
    condition: state
    entity_id: binary_sensor.eight_right_bed_presence
    state: 'off'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bed_occupied

- alias: Bed Presence Input Boolean Turned Off Right Side
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.eight_right_bed_presence
    to: 'off'
  condition:
    condition: state
    entity_id: binary_sensor.eight_left_bed_presence
    state: 'off'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bed_occupied


     #####################################################
     ## Master Bedroom Lamps On With Motion
     #####################################################

- alias: Master Bedroom Lamps On with Motion
  initial_state: true
#  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bedroom_sensor_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.bed_occupied
      state: 'off'
    - condition: numeric_state
      entity_id: 'sensor.master_bedroom_sensor_light_level'
      below: 20
  action:
  - data_template:
      entity_id: light.master_bedroom_lamps
      brightness: "{{ states('input_number.light_brightness') | int }}"
      kelvin: "{{ states('input_number.light_kelvin') | int }}"
#      transition: 15
    service: light.turn_on

     #####################################################
     ## Master Bedroom Lamps and Lights Off Without Motion
     #####################################################

- alias: Master Bedroom Lights Off without Motion
  initial_state: true
#  hide_entity: True
  trigger:
  - entity_id: binary_sensor.master_bedroom_sensor_motion
    platform: state
    to: 'off'
    for: '00:15:00'
  condition:
    - condition: state
      entity_id: input_boolean.bed_occupied
      state: 'off'
  action:
  - data:
      entity_id: 
        - light.master_bedroom_ceiling_lights
        - light.master_bedroom_lamps
    service: light.turn_off