---

#####################################################
## Den Lamps On with Motion
#####################################################

- alias: Den Lamps On with Motion
  initial_state: true
  trigger:
  - platform: state
#custom    entity_id: binary_sensor.den_motion_sensor
    entity_id: binary_sensor.den_sensor_motion
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: 'sensor.den_sensor_light_level'
      below: 20
  action:
  - data_template:
      entity_id: light.den_lamps
      brightness: "{{ states('input_number.light_brightness') | int }}"
      kelvin: "{{ states('input_number.light_kelvin') | int }}"
      transition: 15
    service: light.turn_on