---
- alias: Temperature at Morning
  initial_state: true
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:45:00"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.upstairs
        target_temp_high: 77
    - service: climate.set_temperature
      data:
        entity_id: climate.downstairs
        target_temp_high: 77