---
##########################################################
## Master Bathroom Lights Automation
##########################################################

     #####################################################
     ## Master Bathroom Lights On with Motion
     #####################################################

- alias: Master Bathroom Light On with Motion Awake
  initial_state: true
#  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bathroom_sensor_motion
#custom    entity_id: binary_sensor.master_bathroom_motion_sensor
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: 'sensor.master_bathroom_sensor_light_level'
      below: 20
  action:
  - data_template:
      entity_id: light.master_bathroom_tub_ceiling
      brightness: "{{ states('input_number.light_brightness') | int }}"
      kelvin: "{{ states('input_number.light_kelvin') | int }}"
      transition: 15
    service: light.turn_on

     #####################################################
     ## Master Bathroom Lights Off Without Motion
     #####################################################

- alias: Master Bathroom Lights Off Without Motion
  initial_state: true
#  hide_entity: True
  trigger:
  - entity_id: binary_sensor.master_bathroom_sensor_motion
    platform: state
    to: 'off'
    for: 0:01:00
  condition: []
  action:
  - data:
      entity_id: light.master_bathroom_tub_ceiling
    service: light.turn_off